### ISSUE TITLE
mvcc_wrapper + ninja

### ISSUE THREAD

**Issue by bathmatt** [kokkos/nvcc_wrapper#10]
I brought this up a while ago and re-doing so.  Ninja has much faster compile times for codes, esp for trillions.  However, ninja +nvcc_wrapper causes the whole code to recompile every time, not just modified files.  Me and @crtrott talked about this about a year ago but we never came to a solution

I know RogetP and EricC are also interested in this.
@rppawlo @eric-c-cyr

**Comment by bartlettroscoe** [comment]
I think this issue has been resolved for some time.  The ATDM CUDA builds of Trilinos have been using Ninja for several months now after the merge of #5.

I think this can be closed.
