### ISSUE TITLE
Incorrect Non-GNU Compiler Detection for Kokkos Flags

### ISSUE THREAD

**Issue by nmhamster** [kokkos/nvcc_wrapper#11]
Using `nvcc_wrapper` with PGI 17.7 on POWER8 does not work correctly when compiling for CUDA backend. Kokkos detects the compiler as if it should be GNU (presumably because of NVCC) and so sets flags like `-mcpu=power8 -mtune=power8` which are not valid for PGI. This creates errors when building.

**Comment by nmhamster** [comment]
So the issue might be complicated. Kokkos does not see the internal compiler as PGI (when using `nvcc_wrapper`, it then drops into here:

```
ifeq ($(KOKKOS_INTERNAL_USE_ARCH_POWER8), 1)
  tmp := $(shell echo "\#define KOKKOS_ARCH_POWER8 1" >> KokkosCore_config.tmp )

  ifeq ($(KOKKOS_INTERNAL_COMPILER_PGI), 1)

  else
    # Assume that this is a really a GNU compiler or it could be XL on P8.
    KOKKOS_CXXFLAGS += -mcpu=power8 -mtune=power8
    KOKKOS_LDFLAGS  += -mcpu=power8 -mtune=power8
  endif
endif
```

Which sets the flags that cannot be used.

**Comment by ibaned** [comment]
So the check in `Makefile.kokkos` looks like this:
```make
KOKKOS_INTERNAL_COMPILER_PGI         := $(strip $(shell $(CXX) --version       2>&1 | grep PGI                 | wc -l))
```
Does this mean `nvcc_wrapper` doesn't pass on `--version` as well as it should? What does `nvcc_wrapper --version` produce?

**Comment by nmhamster** [comment]
@ibaned - I have a fix in the Makefile.kokkos to address my second post but it doesn't actually address the bug (I still think we should do that though, watch out for a PR shortly). 

To answer your question:

`$nvcc_wrapper --version` produces the following:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Mon_Jun_26_16:16:41_CDT_2017
Cuda compilation tools, release 9.0, V9.0.102
```

**Comment by ibaned** [comment]
So... should `nvcc_wrapper --version` pass `--version` to the host compiler instead? In theory it would be nice to know that both `nvcc` and the host compiler are in there, but if we have to pick one then based on the checks for `-mcpu` flags etc. the host compiler may be the better choice.

**Comment by nmhamster** [comment]
@ibaned - I wonder if we need a `--host-version` as well because we may need to detect which CUDA version we are using as well.

**Comment by ibaned** [comment]
The trouble I see with `--host-version` is that it is only accepted by `nvcc_wrapper`, so it wouldn't work to check whether users are using un-wrapped PGI to compile for host only... this is definitely tricky.

**Comment by crtrott** [comment]
Forgot all about this issue and was just about to open a new one. I just added the --host-version in a commit, and will now teach our compiler detection to detect that we are using nvcc_wrapper in which case we can detect what the host compiler is and drop into the correct path.
