### ISSUE TITLE
-maxregcount unhandled

### ISSUE THREAD

**Issue by ibaned** [kokkos/nvcc_wrapper#17]
@dholladay00 wrote:
>I have the following compile line:

```
/.../nvcc_wrapper  -D__LOCAL_SOLVER__ ...includes... ...optimizations... -maxrregcount=32 -O3 -DNDEBUG   --std=c++11 --relocatable-device-code=true -expt-extended-lambda -arch=sm_52 -std=c++11 -o /.../Kokkos_Spinwait.cpp.o -c /.../Kokkos_Spinwait.cpp
nvcc_wrapper - *warning* you have set multiple optimization flags (-std=c++1* or --std=c++1*), only the first is used because nvcc can only accept a single std setting
g++: error: unrecognized command line option ‘-maxrregcount=32’
```

>Does that compile option need to be added in a special way in cmake in order to work properly?

**Comment by crtrott** [comment]
Its actually "-maxrregcount 32" without an equal sign. I think all the nvcc arguments don't use an "equal" sign.

**Comment by ibaned** [comment]
Okay, I guess this is wrong usage then. Let us know if removing the equal sign fixes it, @dholladay00

**Comment by dholladay00** [comment]
yep, fixed. Interesting I thought the online example I was looking at had an `=`. Thanks for the help

**Comment by crtrott** [comment]
This is the output from help. Note that nvcc_wrapper might not recognize the two "-" version. 
```
[crtrott@apollo Pthread_Serial-release]$ nvcc --help | grep maxrreg
--maxrregcount <amount>                    (-maxrregcount)                   
        size, thereby reducing the amount of thread parallelism.  Hence, a good maxrregcount
```
