### ISSUE TITLE
Printing nvcc commands as an option durning live usage would nice

### ISSUE THREAD

**Issue by bartlettroscoe** [kokkos/nvcc_wrapper#19]
The current `nvcc_wrapper` script has a dry-run option but that just prints what it would have run and stops.  To help debug issues and just provide more information, it would be nice to have a VERBOSE mode where it would print the command that it is going to run and then run it.

**Comment by ibaned** [comment]
Just merged the relevant pull request

**Comment by bartlettroscoe** [comment]
This has been resolved with the merge of #20.

NOTE: I also created https://github.com/trilinos/Trilinos/pull/3081 which contains a commit https://github.com/trilinos/Trilinos/pull/3081/commits/64738911c27abf6fe87a327d7975874bfc5ba496 which has this patch as well (so we can use it while waiting for `nvcc_wrapper` to get updated in Kokkos and then waiting for the next Kokkos update in Trilinos).

Otherwise, this issue is resolved from my point of view so I am closing.
