### ISSUE TITLE
Recognize xl force-language flag

### ISSUE THREAD

**Issue by theguruat12** [kokkos/nvcc_wrapper#23]
xl can use -+ to force C++ compilation (as opposed to -x c++, which it also supports).  CMake uses -+ when building C++ sources.  Since nvcc doesn't remove this from the line, xl reports that -+ cannot be used with -x.  CMake will likely be removing this option, but for backwards-compatibility with the current (and older) releases, it seems prudent to translate it before handing it off to the compiler.

**Comment by ibaned** [comment]
I think this pull request was accepted... closing.
