### ISSUE TITLE
Add cudart and cudadevrt to recognized options

### ISSUE THREAD

**Issue by mpokorny** [kokkos/nvcc_wrapper#32]
It would be convenient (to me, at least) to have nvcc_wrapper recognize the `-cudart`, `--cudart`, `-cudadevrt` and `--cudadevrt` options to `nvcc`. It's a simple change, I think; I've already done it in my local version, and I could provide a PR for the changes if you'd like.

**Comment by masterleinad** [comment]
Fell free to provide a pull request to the `develop` branch of https://github.com/kokkos/kokkos/.
